# Generated by Django 5.1.3 on 2024-12-05 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0003_alter_lead_assigned_to_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='leads',
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web01.company', verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[(1, '男'), (2, '女')], default=1, max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web01.employee', verbose_name='负责人'),
        ),
    ]
