# Generated by Django 5.1.3 on 2024-12-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0004_remove_customer_leads_customer_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, max_length=10, verbose_name='性别'),
        ),
    ]
