# Generated by Django 5.1.3 on 2024-12-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '已完成'), (1, '未完成')], default=1, verbose_name='状态'),
        ),
    ]
