# Generated by Django 5.1.3 on 2024-12-08 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0012_customer_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followuprecord',
            name='lead',
        ),
        migrations.AddField(
            model_name='followuprecord',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web01.customer', verbose_name='客户'),
            preserve_default=False,
        ),
    ]
