# Generated by Django 5.1.3 on 2024-12-08 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0014_admin_department_admin_email_admin_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='department',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='web01.department', verbose_name='部门'),
        ),
    ]
