# Generated by Django 5.1.3 on 2024-12-08 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0015_alter_admin_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.department', verbose_name='部门'),
        ),
    ]
